### ISSUE TITLE
Layout überarbeiten

### ISSUE THREAD

**Issue by rhaetscher** [sleepyRias/BetterSteam#60]
Sucht Inspiration in ähnlichen Apps und posted hier Screenshots wie das Layout mal werden soll.

**Comment by sleepyRias** [comment]
nein

**Comment by Multi538** [comment]
https://099.supply/?ref=godly (layout und animationen sind smooth)
https://chester.how/?ref=godly (der hover auf den boxen ist nice)
https://mishmash.pt/?ref=godly (ist relativ simple und dennoch slick) 
![image](https://github.com/sleepyRias/RASandbox/assets/59820274/a636bfda-cbc2-4c08-bea1-ab05d3a6c3a9)

**Comment by sleepyRias** [comment]
ich übernehme das mal und fange mit eher barebone styling an, bis wir zeit für polishing haben
